#!/usr/bin/env python3

import argparse
import json
from pathlib import Path
import numpy as np


def load_channel(root, ch):
    meta_path = root / f"csi_pdu_ch{ch}.jsonl"
    bin_path = root / f"csi_pdu_ch{ch}.bin"

    records = []

    with open(meta_path) as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))

    H = np.fromfile(
        bin_path,
        dtype=np.complex64,
    )

    if len(H) % 52 != 0:
        raise RuntimeError(
            f"{bin_path}: CSI size is not divisible by 52"
        )

    H = H.reshape(-1, 52)

    if len(records) != len(H):
        raise RuntimeError(
            f"RX{ch}: metadata={len(records)}, CSI={len(H)}"
        )

    out = {}

    for rec, h in zip(records, H):
        seq = int(rec["seq"])

        if seq in out:
            raise RuntimeError(
                f"RX{ch}: duplicate seq {seq}"
            )

        out[seq] = {
            "meta": rec,
            "H": h,
        }

    return out


def main():
    ap = argparse.ArgumentParser()

    ap.add_argument(
        "capture_dir",
        type=Path,
    )

    ap.add_argument(
        "--snr-min",
        type=float,
        default=10.0,
    )

    ap.add_argument(
        "--output",
        type=Path,
        default=None,
    )

    args = ap.parse_args()

    root = args.capture_dir

    rx0 = load_channel(root, 0)
    rx1 = load_channel(root, 1)

    common = sorted(
        set(rx0) & set(rx1)
    )

    # Quality gate.
    valid = []

    for seq in common:
        s0 = float(
            rx0[seq]["meta"].get("snr", -999)
        )
        s1 = float(
            rx1[seq]["meta"].get("snr", -999)
        )

        if s0 >= args.snr_min and s1 >= args.snr_min:
            valid.append(seq)

    if not valid:
        raise RuntimeError(
            "No valid common CSI packets"
        )

    #
    # Physical TDM mapping established by TX0-only
    # calibration:
    #
    #   even MAC sequence -> physical TX0
    #   odd  MAC sequence -> physical TX1
    #
    valid_set = set(valid)

    cycles = []

    for even_seq in valid:
        if even_seq % 2 != 0:
            continue

        odd_seq = (even_seq + 1) % 4096

        if odd_seq not in valid_set:
            continue

        cycles.append(
            (even_seq, odd_seq)
        )

    if not cycles:
        raise RuntimeError(
            "No complete even/odd TDM cycles found"
        )

    H = np.zeros(
        (
            len(cycles),
            52,
            2,
            2,
        ),
        dtype=np.complex64,
    )

    seq_table = np.zeros(
        (len(cycles), 2),
        dtype=np.int32,
    )

    snr = np.zeros(
        (
            len(cycles),
            2,
            2,
        ),
        dtype=np.float32,
    )

    cfo = np.zeros(
        (
            len(cycles),
            2,
            2,
        ),
        dtype=np.float32,
    )

    #
    # Timestamp layout:
    #
    # [cycle, rx, tx_slot]
    #
    # tx_slot 0 = physical TX0 / even seq
    # tx_slot 1 = physical TX1 / odd seq
    #
    timestamp_monotonic_ns = np.full(
        (
            len(cycles),
            2,
            2,
        ),
        -1,
        dtype=np.int64,
    )

    timestamp_wall_ns = np.full(
        (
            len(cycles),
            2,
            2,
        ),
        -1,
        dtype=np.int64,
    )


    #
    # RF sample-domain frame-start index.
    #
    # Layout:
    #   [cycle, rx, tx_slot]
    #
    # Generated by sync_short from nitems_read() in the
    # continuous 5 MHz UHD input stream.
    #
    rf_sample_index = np.full(
        (
            len(cycles),
            2,
            2,
        ),
        -1,
        dtype=np.int64,
    )

    for n, (seq_even, seq_odd) in enumerate(cycles):

        seq_table[n] = [
            seq_even,
            seq_odd,
        ]

        # Physical TX0 = even MAC sequence
        H[n, :, 0, 0] = rx0[seq_even]["H"]
        H[n, :, 1, 0] = rx1[seq_even]["H"]

        # Physical TX1 = odd MAC sequence
        H[n, :, 0, 1] = rx0[seq_odd]["H"]
        H[n, :, 1, 1] = rx1[seq_odd]["H"]

        for rx in (0, 1):
            src = rx0 if rx == 0 else rx1

            for txslot, seq in enumerate(
                (seq_even, seq_odd)
            ):
                m = src[seq]["meta"]

                snr[n, rx, txslot] = float(
                    m.get("snr", np.nan)
                )

                cfo[n, rx, txslot] = float(
                    m.get(
                        "frequency_offset",
                        np.nan,
                    )
                )

                timestamp_monotonic_ns[
                    n, rx, txslot
                ] = int(
                    m.get(
                        "host_monotonic_ns",
                        -1,
                    )
                )

                timestamp_wall_ns[
                    n, rx, txslot
                ] = int(
                    m.get(
                        "host_wall_time_ns",
                        -1,
                    )
                )


                rf_sample_index[
                    n, rx, txslot
                ] = int(
                    m.get(
                        "rf_sample_index",
                        -1,
                    )
                )

    #
    # --------------------------------------------------------
    # Nominal TX sequence time base
    # --------------------------------------------------------
    #
    # Physical TDM transmission currently uses one MAC packet
    # every 100 ms:
    #
    #   even seq -> physical TX0
    #   odd  seq -> physical TX1
    #
    # We unwrap the 12-bit MAC sequence number and reconstruct
    # the nominal TX scheduling time. Missing packets therefore
    # preserve elapsed nominal time instead of compressing it.
    #
    # IMPORTANT:
    # This is NOT a UHD hardware RF timestamp.
    #
    tx_packet_interval_s = 0.100

    seq_even_raw = (
        seq_table[:, 0]
        .astype(np.int64)
    )

    seq_even_unwrapped = np.empty_like(
        seq_even_raw,
        dtype=np.int64,
    )

    seq_even_unwrapped[0] = (
        seq_even_raw[0]
    )

    for n in range(
        1,
        len(seq_even_raw)
    ):
        prev_raw = (
            seq_even_raw[n - 1]
        )

        cur_raw = (
            seq_even_raw[n]
        )

        delta = (
            cur_raw
            - prev_raw
        )

        if delta < -2048:
            delta += 4096

        elif delta > 2048:
            delta -= 4096

        seq_even_unwrapped[n] = (
            seq_even_unwrapped[n - 1]
            + delta
        )

    cycle_time_nominal_s = (
        (
            seq_even_unwrapped
            - seq_even_unwrapped[0]
        )
        * tx_packet_interval_s
    ).astype(np.float64)

    packet_time_nominal_s = np.stack(
        [
            cycle_time_nominal_s,
            cycle_time_nominal_s
            + tx_packet_interval_s,
        ],
        axis=1,
    )


    #
    # --------------------------------------------------------
    # RF sample-domain time base
    # --------------------------------------------------------
    #
    # sync_short receives the UHD stream directly at 5 MHz.
    # Therefore rf_sample_index is expressed in UHD-stream
    # complex samples.
    #
    # This is a relative sample-domain RF time base.
    # It is NOT an absolute UHD hardware timestamp.
    #
    rf_sample_rate_hz = 5_000_000.0

    rf_sample_time_valid = bool(
        np.all(
            rf_sample_index >= 0
        )
    )

    if rf_sample_time_valid:

        #
        # Global relative origin from the first physical-TX0
        # packet. RX0/RX1 are retained in the same sample
        # reference so their small detection skew remains
        # observable.
        #
        rf_reference_sample_index = int(
            np.rint(
                np.median(
                    rf_sample_index[
                        0,
                        :,
                        0,
                    ]
                )
            )
        )

        rf_time_relative_s = (
            (
                rf_sample_index.astype(
                    np.float64
                )
                - rf_reference_sample_index
            )
            / rf_sample_rate_hz
        )

        #
        # One representative RF time per TDM cycle.
        # Use physical TX0 and median across the two RX chains.
        #
        rf_cycle_time_s = np.median(
            rf_time_relative_s[
                :,
                :,
                0,
            ],
            axis=1,
        )

        #
        # RX1 - RX0 frame-start skew, in input-stream samples.
        #
        rf_rx_sample_skew = (
            rf_sample_index[
                :,
                1,
                :,
            ]
            - rf_sample_index[
                :,
                0,
                :,
            ]
        ).astype(np.int64)

    else:

        rf_reference_sample_index = -1

        rf_time_relative_s = np.full(
            rf_sample_index.shape,
            np.nan,
            dtype=np.float64,
        )

        rf_cycle_time_s = np.full(
            len(cycles),
            np.nan,
            dtype=np.float64,
        )

        rf_rx_sample_skew = np.full(
            (
                len(cycles),
                2,
            ),
            0,
            dtype=np.int64,
        )

    if args.output is None:
        args.output = (
            root
            / "H_raw_tdm_physical_2x2.npz"
        )

    np.savez_compressed(
        args.output,
        H_raw=H,
        seq=seq_table,
        snr=snr,
        cfo_hz=cfo,


        rf_sample_index=
            rf_sample_index,

        rf_sample_rate_hz=np.float64(
            rf_sample_rate_hz
        ),

        rf_reference_sample_index=np.int64(
            rf_reference_sample_index
        ),

        rf_time_relative_s=
            rf_time_relative_s,

        rf_cycle_time_s=
            rf_cycle_time_s,

        rf_rx_sample_skew=
            rf_rx_sample_skew,

        rf_sample_time_valid=np.bool_(
            rf_sample_time_valid
        ),

        sample_domain_time_valid=np.bool_(
            rf_sample_time_valid
        ),

        rf_time_source=np.array(
            "sync_short_continuous_sample_index"
        ),

        uhd_absolute_time_valid=np.bool_(
            False
        ),

        timestamp_monotonic_ns=
            timestamp_monotonic_ns,

        timestamp_wall_ns=
            timestamp_wall_ns,

        timestamp_source=np.array(
            "host_decoded_csi_handler"
        ),

        packet_time_nominal_s=
            packet_time_nominal_s,

        cycle_time_nominal_s=
            cycle_time_nominal_s,

        tx_packet_interval_s=np.float64(
            tx_packet_interval_s
        ),

        nominal_time_source=np.array(
            "mac_sequence_plus_tx_packet_interval"
        ),

        hardware_rf_timestamp_valid=np.bool_(
            False
        ),

        fc_hz=np.float64(5.89e9),
        nsub=np.int32(52),
        rx_count=np.int32(2),
        tx_slot_count=np.int32(2),
        tx_mapping=np.array(
            [
                "physical_TX0_even_seq",
                "physical_TX1_odd_seq",
            ]
        ),
        physical_tx_mapping_valid=np.bool_(True),
    )

    print("capture:", root)
    print("common packets:", len(common))
    print("quality-valid packets:", len(valid))
    print("complete TDM cycles:", len(cycles))
    print("H_raw shape:", H.shape)
    print("sequences:")
    print(seq_table)
    print("output:", args.output)

    print()
    print(
        "Physical TX mapping: "
        "tx=0 -> TX0/even-seq, "
        "tx=1 -> TX1/odd-seq"
    )


if __name__ == "__main__":
    main()
