#!/usr/bin/env python3

import os
import json
import numpy as np
import pmt
from gnuradio import gr


class csi_tag_collector(gr.sync_block):
    """
    Collect CSI generated by ieee802_11.frame_equalizer.

    frame_equalizer adds a 'csi' tag after decoding SIGNAL.
    The tag already contains LS CSI estimated from both L-LTF symbols.
    """

    def __init__(self, rx_chan=0, bin_path=None, meta_path=None):
        gr.sync_block.__init__(
            self,
            name=f"csi_tag_collector_rx{rx_chan}",
            # frame_equalizer output:
            # one GNU Radio item = 48 uint8 data subcarriers
            in_sig=[(np.uint8, 48)],
            out_sig=None,
        )

        self.rx_chan = int(rx_chan)

        self.key_csi = pmt.intern("csi")
        self.key_snr = pmt.intern("snr")
        self.key_freq = pmt.intern("nominal frequency")
        self.key_foff = pmt.intern("frequency offset")
        self.key_beta = pmt.intern("beta")
        self.key_encoding = pmt.intern("encoding")
        self.key_frame_bytes = pmt.intern("frame bytes")

        self.bin_path = bin_path
        self.meta_path = meta_path

        self.bin_fh = None
        self.meta_fh = None

        self.frame_idx = 0

        if self.bin_path:
            os.makedirs(
                os.path.dirname(self.bin_path),
                exist_ok=True,
            )
            self.bin_fh = open(self.bin_path, "wb")

        if self.meta_path:
            os.makedirs(
                os.path.dirname(self.meta_path),
                exist_ok=True,
            )
            self.meta_fh = open(
                self.meta_path,
                "w",
                buffering=1,
            )

    @staticmethod
    def _number(v):
        try:
            if pmt.is_integer(v):
                return int(pmt.to_long(v))

            if pmt.is_real(v):
                return float(pmt.to_double(v))
        except Exception:
            pass

        return None

    def work(self, input_items, output_items):
        x = input_items[0]
        n = len(x)

        if n == 0:
            return 0

        start = self.nitems_read(0)
        end = start + n

        tags = self.get_tags_in_range(
            0,
            start,
            end,
        )

        #
        # Group tags by absolute output offset because frame_equalizer
        # writes CSI/SNR/frequency/etc. at the same item.
        #
        groups = {}

        for tag in tags:
            groups.setdefault(
                int(tag.offset),
                {},
            )[tag.key] = tag.value

        for offset in sorted(groups):
            d = groups[offset]

            if self.key_csi not in d:
                continue

            try:
                H = np.asarray(
                    pmt.c32vector_elements(
                        d[self.key_csi]
                    ),
                    dtype=np.complex64,
                )
            except Exception as e:
                print(
                    f"[CSI-TAG-COLLECT] "
                    f"RX{self.rx_chan} invalid CSI tag: {e}"
                )
                continue

            if H.size != 52:
                print(
                    f"[CSI-TAG-COLLECT] "
                    f"RX{self.rx_chan} unexpected CSI length "
                    f"{H.size}"
                )
                continue

            self.frame_idx += 1

            if self.bin_fh:
                H.tofile(self.bin_fh)
                self.bin_fh.flush()

            rec = {
                "csi_idx": self.frame_idx,
                "rx_chan": self.rx_chan,
                "stream_offset": int(offset),
                "csi_len": int(H.size),
                "abs_mean": float(np.mean(np.abs(H))),
            }

            mapping = (
                ("snr", self.key_snr),
                ("nominal_frequency", self.key_freq),
                ("frequency_offset", self.key_foff),
                ("beta", self.key_beta),
                ("encoding", self.key_encoding),
                ("frame_bytes", self.key_frame_bytes),
            )

            for name, key in mapping:
                if key in d:
                    val = self._number(d[key])
                    if val is not None:
                        rec[name] = val

            if self.meta_fh:
                self.meta_fh.write(
                    json.dumps(rec) + "\n"
                )

            if self.frame_idx <= 20 or self.frame_idx % 100 == 0:
                print(
                    f"[CSI-TAG-COLLECT] "
                    f"RX{self.rx_chan} "
                    f"idx={self.frame_idx} "
                    f"offset={offset} "
                    f"mean={rec['abs_mean']:.6f} "
                    f"snr={rec.get('snr')}"
                )

        return n

    def stop(self):
        try:
            if self.bin_fh:
                self.bin_fh.close()
        except Exception:
            pass

        try:
            if self.meta_fh:
                self.meta_fh.close()
        except Exception:
            pass

        return True
